---
name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          swift test --enable-test-discovery --enable-code-coverage
      - name: Convert coverage files
        run: |
          llvm-cov export -format="lcov" \
            .build/debug/AdventKitPackageTests.xctest \
            -ignore-filename-regex="\/Tests\/" \
            -instr-profile .build/debug/codecov/default.profdata > info.lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          file: info.lcov
