---
name: Tests

on:
  push:
  pull_request:

jobs:
  swift-job:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Platform check
        run: uname -a

      - name: swift info
        run: swift --version

      - name: Build
        run: |
          cd Sources/AdventKit
          swift build -c release

      - name: Test
        run: |
          cd Sources/AdventKit
          swift test  --enable-code-coverage --verbose
