---
name: Tests

on:
  push:
  pull_request:

jobs:
  swift-job:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Platform check
        run: uname -a

      - name: swift info
        run: swift --version

      - name: Build
        run: |
          cd Sources/AdventKit
          swift build -c release

      - name: Test
        run: |
          cd Sources/AdventKit
          swift test  --enable-code-coverage --verbose

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.5.0

      - name: Convert coverage data
        run: |
          llvm-cov export -formal="lcov" .build/debug/AdventKitTests.xctest/Contents/MacOS/AdventKitTests -instr-profile .build/debug/codecov/default.profdata > info.lcov

      - uses: codecov/codecov-action@v2
        with:
          files: "*"
          fail_ci_if_error: false
          verbose: true

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: AdventKit-artifact
          path: ${{ github.workspace }}
