---
name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "swift:5.2-bionic"
          - "swift:5.3-bionic"
          - "swift:5.4-bionic"
          - "swift:5.5-bionic"
          - "swift:5.5-focal"
          - "swift:5.5-amazonlinux2"
          - "swift:5.5-centos8"

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Platform check
        run: uname -a

      - name: swift info
        run: swift --version

      - name: Test
        run: |
          swift test --enable-test-discovery --enable-code-coverage

      - name: Convert coverage files
        run: |
          llvm-cov export -format="lcov" \
            .build/debug/AdventKitPackageTests.xctest \
            -ignore-filename-regex="\/Tests\/" \
            -instr-profile .build/debug/codecov/default.profdata > info.lcov

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          file: info.lcov
          verbose: true

      - name: Upload reports as artifact at failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: AdventKit-artifact
          path: ${{ github.workspace }}
