---
name: Tests

on:
  push:
  pull_request:

jobs:
  swift-job:
    runs-on: macos-latest

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Platform check
        run: uname -a

      - name: swift info
        run: swift --version

      - name: Build
        run: |
          swift build

      - name: Test
        run: |
          swift test  --enable-code-coverage --show-codecov-path --verbose
          xcrun llvm-cov export -format "lcov" \
            .build/debug/AdventKitPackageTests.xctest/Contents/MacOs/AdventKitPackageTests \
            -instr-profile=.build/debug/codecov/default.profdata > info.lcov
          bash (<curl https://codecov.io/bash)

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          file: info.lcov
          verbose: true

      - name: Upload reports as artifact at failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: AdventKit-artifact
          path: ${{ github.workspace }}
