---
name: Tests

on:
  push:
  pull_request:

jobs:
  swift-job:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Platform check
        run: uname -a

      - name: swift info
        run: swift --version

      - name: Build
        run: |
          cd Sources/AdventKit
          swift build -c release

      - name: Test
        run: |
          cd Sources/AdventKit
          swift test  --enable-code-coverage --show-codecov-path --verbose

      - name: Install swift and llvm
        uses: slashmo/install-swift@v0.1.0
        # run: |
        #   sudo apt-get install -y llvm
        #   which llvm-cov

      - name: Convert coverage data # llvm-cov export -format="lcov" .build/debug/AdventKitPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
        run: |
          llvm-cov export -format="lcov" ".build/x86_64-apple-macosx/debug/codecov/AdventKit.json" -instr-profile ".build/debug/codecov/default.profdata" > info.cov
          bash <(curl https://codecov.io/bash)
      - uses: codecov/codecov-action@v2
        with:
          files: "*"
          fail_ci_if_error: false
          verbose: true

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: AdventKit-artifact
          path: ${{ github.workspace }}
